addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.16")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.24")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.6")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"   % "3.9.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"        % "2.0.1")
