name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests - Scala 2.13
      run: sbt "++ 2.13.4 ;fmtCheck ;test"
    - name: Run tests - Scala 3.0
      run: sbt "++ 3.0.0 test"
